"""Celery-backed implementation of :class:`ITaskQueue` (CAP-005).

Wraps the Celery primitives defined in :mod:`zubot_ingestion.services.celery_app`
behind the synchronous :class:`ITaskQueue` interface declared in
``zubot_ingestion.domain.protocols``. Two responsibilities:

    1. Enqueue an extraction job onto the default queue and return the
       Celery task ID for status tracking.
    2. Look up the current state of a previously-enqueued task and translate
       Celery's native state strings into a :class:`TaskStatus` DTO.

Celery's native state strings (``PENDING``, ``STARTED``, ``SUCCESS``,
``FAILURE``, ``RETRY``) line up exactly with the
``Literal[...]`` accepted by :class:`TaskStatus.state`, so no remapping table
is required. Any other state (e.g. ``REVOKED``) is collapsed to ``PENDING``
defensively.

Layering: this module lives in the application (services) layer. It depends
on :mod:`zubot_ingestion.shared.types` and the Celery app object, never on
the ``infrastructure`` or ``api`` layers.
"""

from __future__ import annotations

import traceback as tb
from typing import Any, cast
from uuid import UUID

from celery.result import AsyncResult

from zubot_ingestion.services.celery_app import app, extract_document_task
from zubot_ingestion.shared.types import TaskStatus

# Celery's documented task states that we expose verbatim through TaskStatus.
_KNOWN_STATES: frozenset[str] = frozenset(
    {"PENDING", "STARTED", "SUCCESS", "FAILURE", "RETRY"}
)


class CeleryTaskQueue:
    """Concrete :class:`ITaskQueue` backed by Celery + Redis.

    Designed to satisfy the structural protocol declared at
    ``zubot_ingestion.domain.protocols.ITaskQueue``. Method signatures match
    that protocol exactly: ``enqueue_extraction(job_id: UUID) -> str`` and
    ``get_task_status(task_id: str) -> TaskStatus``.
    """

    def enqueue_extraction(self, job_id: UUID) -> str:
        """Enqueue ``extract_document_task`` for the given ``job_id``.

        The Celery task signature accepts a string job id (JSON-serializable),
        so we coerce the :class:`UUID` to its canonical string form before
        calling ``.delay()``. Returns the Celery-generated task id, which the
        caller persists alongside the job record for later status lookups.

        Args:
            job_id: UUID of the job to process.

        Returns:
            Celery task ID (a string UUID generated by Celery itself).
        """
        async_result = extract_document_task.delay(str(job_id))
        return cast(str, async_result.id)

    def get_task_status(self, task_id: str) -> TaskStatus:
        """Wrap a Celery :class:`AsyncResult` lookup behind the DTO.

        Translation rules:

            * ``state`` is passed through verbatim if it is one of the five
              known states; any other Celery state (e.g. ``REVOKED`` or a
              custom state) is reported as ``PENDING`` so the consumer can
              treat the task as "not yet known to be done".
            * ``result`` is populated only on ``SUCCESS`` (the actual task
              return value). On any other state it is ``None``.
            * ``traceback`` is populated only on ``FAILURE``, formatted as a
              string for transport over the wire.

        Args:
            task_id: Celery task ID returned from a prior ``enqueue_extraction``.

        Returns:
            :class:`TaskStatus` snapshot of the task at the moment of lookup.
        """
        async_result: AsyncResult = AsyncResult(task_id, app=app)
        raw_state = async_result.state
        state = raw_state if raw_state in _KNOWN_STATES else "PENDING"

        result_value: Any | None = None
        traceback_value: str | None = None

        if state == "SUCCESS":
            try:
                result_value = async_result.result
            except Exception:
                # If the result backend deserialization itself blows up, fall
                # back to None rather than propagating — the consumer only
                # wants a snapshot, not a re-raise of the task error.
                result_value = None
        elif state == "FAILURE":
            failure = async_result.result
            if isinstance(failure, BaseException):
                traceback_value = "".join(
                    tb.format_exception(type(failure), failure, failure.__traceback__)
                )
            elif async_result.traceback is not None:
                traceback_value = str(async_result.traceback)
            else:
                traceback_value = repr(failure) if failure is not None else None

        return TaskStatus(
            state=state,  # type: ignore[arg-type]
            result=result_value,
            traceback=traceback_value,
        )


__all__ = ["CeleryTaskQueue"]
